/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.coderoria.syncedhearts;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
