/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.coderoria.syncedhearts;

import org.bukkit.plugin.java.JavaPlugin;

public class Main extends JavaPlugin {

  @Override
  public void onEnable() {

  }

  public void onDisable() {
    
  }

}
